export const getCategoryConstent = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};

export const getProductConstent = {
  GET_ALL_PRODUCT_BY_SLUG_REQUEST: "GET_ALL_PRODUCT_BY_SLUG_REQUEST",
  GET_ALL_PRODUCT_BY_SLUG_SUCCESS: "GET_ALL_PRODUCT_BY_SLUG_SUCCESS",
  GET_ALL_PRODUCT_BY_SLUG_FAILURE: "GET_ALL_PRODUCT_BY_SLUG_FAILURE",

  GET_ALL_PRODUCT_DETAIL_BY_ID_REQUEST: "GET_ALL_PRODUCT_DETAIL_BY_ID_REQUEST",
  GET_ALL_PRODUCT_DETAIL_BY_ID_SUCCESS: "GET_ALL_PRODUCT_DETAIL_BY_ID_SUCCESS",
  GET_ALL_PRODUCT_DETAIL_BY_ID_FAILURE: "GET_ALL_PRODUCT_DETAIL_BY_ID_FAILURE",
};

export const pageProductConstent = {
  PAGE_PRODUCT_REQUEST: "PAGE_PRODUCT_REQUEST",
  PAGE_PRODUCT_SUCCESS: "PAGE_PRODUCT_SUCCESS",
  PAGE_PRODUCT_FAILURE: "PAGE_PRODUCT_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  RESET_CART: "RESET_CART",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_FAILURE: "GET_CART_FAILURE",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
};
