export const getCategoryConstent = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};

export const getProductConstent = {
  GET_ALL_PRODUCT_BY_SLUG_REQUEST: "GET_ALL_PRODUCT_BY_SLUG_REQUEST",
  GET_ALL_PRODUCT_BY_SLUG_SUCCESS: "GET_ALL_PRODUCT_BY_SLUG_SUCCESS",
  GET_ALL_PRODUCT_BY_SLUG_FAILURE: "GET_ALL_PRODUCT_BY_SLUG_FAILURE",
};
